version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - /home/ubuntu/telegraf-influxdb-grafana/influxdb:/var/lib/influxdb2
      - /home/ubuntu/telegraf-influxdb-grafana/config:/etc/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/telegraf-influxdb-grafana/grafana:/var/lib/grafana     
      - /home/ubuntu/telegraf-influxdb-grafana/grafana.ini:/etc/grafana/grafana.ini
      - /home/ubuntu/telegraf-influxdb-grafana/ssl/certs:/etc/ssl/certs
    links:
      - influxdb
    user: 472:472
    restart: always
      
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    network_mode: "host"
    volumes:
      -  /home/ubuntu/telegraf-influxdb-grafana/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
      
  chronograf:
    container_name: chronograf
    image: chronograf:latest
    volumes:
      - /home/ubuntu/telegraf-influxdb-grafana/chronograf_data:/var/lib/chronograf
    ports:
      - 8888:8888
    links:
      - influxdb
    restart: always

  # kapacitor:
  #     image: kapacitor
  #     environment:
  #       KAPACITOR_HOSTNAME: kapacitor
  #       # KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
  #     volumes:
  #       - ./kapacitor/data:/var/lib/kapacitor
  #     links:
  #       - influxdb
  #     ports:
  #       - "9092:9092"